---
{"dg-publish":true,"permalink":"/atlas/zametki/dokumentacziya/0-java-dlya-nachinayushhih-level-2/08-isklyucheniya/","tags":["Java"],"noteIcon":"","created":"2023-12-12T23:22:55.968+05:00","updated":"2025-04-07T02:08:40.607+05:00"}
---


## 001 Обработка исключений. Теория. Часть 1

Самый базовый класс в исключений является `Throwable`. У нас есть два основных наследника от нашего класса `Throwable` это `Error` и `Exception`. `Error` – это ошибки которые в принципе мы не можем ничего сделать.(Например когда у нас закончилась место в нашей области памяти). В таком случае наша программе не может продолжать выполнение и экстренно завершается. `Exception` – С этим исключением мы уже можем что-то сделать. В свою очередь она тоже делится на два больших категорий. Это `RuntimeException` и все остальные. Исключений - это обычные объекты какого-то класса из иерархий исключений. Для того чтобы бросить исключение мы должны использовать `throw`, после мы должны передать объект исключения. Чтобы подбросить исключение мы должны после сигнатуры метода написать ключевое слово `throws`, это значит наш метод подбрасывает какой-то исключение. Для обработки исключение нам необходимо использовать новое ключевое слово `try` и открываем фигурные скобки, и переносим любой код который может подбрасывать исключение в этот блок `try`. Далее мы должны указать следующий блок – `catch`. То есть какое именно исключение мы ловим который может подбросить в блоке `try`. И в блоке `catch` мы можем как-то обработать наше исключение. Как только мы отловили наше исключение мы дальше можем выполнять наш код.

[github.com](https://github.com/dmdev2020/java-level2-starter/tree/lesson-20.1/src/com/dmdev/oop/lesson20)

## 002 Обработка исключений. Теория. Часть 2

Блок `finally` – используется после блоков `try` и `catch`. Отличие блока `finally` в том что он выполняется всегда, было ли у нас исключение или нет. Таким образом у нас есть возможность выполнить какой-то код обязательно. Обычно блок `finally` используется для очистки каких-то ресурсов. `RuntimeException` – не отлавливаемые исключений, то есть мы не обязаны его отлавливать. Оно используется для таких ситуации как выход за пределы массива.

[github.com](https://github.com/dmdev2020/java-level2-starter/tree/lesson-20.1/src/com/dmdev/oop/lesson20)

## 003 Обработка исключений. Практика

>Tasks.txt
>	1. Объявите переменную со значением null. Вызовите метод у этой переменной. Отловите возникшее исключение.
>	2. Написать код, который создаст, а затем отловит ArrayIndexOutOfBoundsException.
>	3. Создать собственный класс-исключение - наследник класса Exception. Создать метод, выбрасывающий это исключение. Вызвать этот метод и отловить исключение. Вывести stack trace в консоль.
>	4. Повторить предыдущее упражнение, но наследуя свой класс от класса RuntimeException. Добавить в конструктор своего класса возможность указания сообщения.
>	5. Бросить одно из существующих в JDK исключений, отловить его и выбросить своё собственное, указав в качестве причины отловленное.
>	6. Создать метод случайным образом выбрасывающий одно из 3-х видов исключений. Вызвать этот метод в блоке try-catch, отлавливающем любое из 3-х.
>	7. Написать метод, который в 50% случаев бросает исключение. Вызвать этот метод в конструкции try-catch-finally. Протестировать работу блока finally.

[github.com](https://github.com/dmdev2020/java-level2-starter/tree/lesson-20.1/src/com/dmdev/oop/lesson20)